<?php 
function new_page_menu() {
     $items = array();
     $items['services'] = array(
        'drupal_formation'             =>  'Nouvelle Page',  //page title
        'description'       =>  'new_page Information',  //description show when mouse hover on link
       	'type' => MENU_NORMAL_ITEM, // add in the custom menu like a link
        'page callback'     =>  'new_page_create',  //callback function which is invoked when menu item is called.
        'access callback'   =>  true,  //any user can access this page
       );
      return $items;

}
/*
* implement hook_theme()
*/
function new_page_theme() {
        $themes = array();
        $themes['my_new_page'] = array(
        'variables' => array(),
        'template' => 'templates/my_new_page',
        'path' => drupal_get_path('module', 'new_page'),
      );
     return $themes;

}
/*
* implement page callback()
*/
function new_page_create() {
  return theme('my_new_page');
}